libsslsupport/wrapper.c

The check to see if *str is non-zero while also checking to
see if it is a space char is redundant, one just needs to
check to see if *str is a space.  Remove the redundant check.
Signed-off-by: Colin Ian King <colin.king@canonical.com>

libsslsupport: remove redundant *str check

---

libkernelflinger/vars.c

Just output log instead of show error info.
Also tune some log format about read/write rollback index.
Tracked-On: OAM-85631
Signed-off-by: Ming Tan <ming.tan@intel.com>

Don't show error when EFI variable RollbackIndex_0000 is not found.

---

Android.mk
avb/libavb/uefi_avb_ops.c
include/libkernelflinger/storage.h
kernelflinger.c
libfastboot/fastboot_oem.c
libkernelflinger/rpmb/rpmb_storage.c
libkernelflinger/security_efi.c
libkernelflinger/storage.c
libkernelflinger/vars.c
ux.c
ux.h

1. Add a new macro KERNELFLINGER_SUPPORT_LIVE_BOOT for support live boot.
2. Default setting is disabled.
3. Live boot is only supported in eng and userdebug build.
4. Now set KERNELFLINGER_SUPPORT_USB_STORAGE = true only support USB
storage.
5. Need set both of KERNELFLINGER_SUPPORT_LIVE_BOOT = true and
KERNELFLINGER_SUPPORT_USB_STORAGE = true to enable USB live boot.
6. Show warning message when booting.
7. Does not save the lock/unlock state to storage.
8. Set to unlock state.
9. Verify boot status is set to orange.
10. Does not read and update the rollback index.
Tracked-On: OAM-85331
Signed-off-by: Ming Tan <ming.tan@intel.com>

Tune the live boot support.

---

libkernelflinger/trusty_efi.c

Sometimes, the expected base address could be used already.
Change-Id: Id53926e4aaa1526067096dd8482dabada5e02fe0
Tracked-On: OAM-85653
Signed-off-by: Tang, Haoyu <haoyu.tang@intel.com>
Reviewed-On: 679796

allocate memory for VMM/TOS as possible

---

include/libkernelflinger/lib.h
libsslsupport/openssl_support.h

There are same line of 'typedef UINTN size_t;' in following files:
libsslsupport/openssl_support.h
include/libkernelflinger/lib.h
Tracked-On: OAM-86760
Signed-off-by: Ming Tan <ming.tan@intel.com>

Fix the compile warning of size_t redefined.

---

libkernelflinger/firststage_mount.c

iasl is updating from 20150619 to 20190816, the name of generated
hexadecimal aml table has changed from "AmlCode" to "FILENAME_aml_code".
Update the variable to align this change.
Tracked-On: OAM-85379
Signed-off-by: Chen, ZhiminX <zhiminx.chen@intel.com>

Update firststage mount config variable name

---

libkernelflinger/Android.mk
libkernelflinger/android.c
libkernelflinger/firststage_mount.c

The early mount table is revised by BIOS and osloader before
loading by kernel, it generates the difference between the source
table from acpi/acpio partitons and the destination table from
kernel, which can not pass VTS check. So integrate early mount
table directly, rather than load it from acpi/acpio partitons.
Tracked-On: OAM-86713
Signed-off-by: Chen, ZhiminX <zhiminx.chen@intel.com>

Remove early mount's dependency for acpi/acpio partitons

---

libkernelflinger/android.c

Tracked-On: OAM-88097
Signed-off-by: Haoyu Tang <haoyu.tang@intel.com>

Fix compile error when both USE_ACPIO and USE_FIRSTSTAGE_MOUNT disabled

---

doc/crashmode.md
libadb/Android.mk
libadb/devmem.c
libadb/hexdump.c
libadb/ioport.c
libadb/ioport.h
libadb/lspci.c
libadb/lspci.h
libadb/pci_class.c
libadb/pci_class.h
libadb/shell_service.c
libadb/shell_service.h

It turns out that when working on issue with regard to BIOS PCI/PCIe enumeration it is handy to be able to enumerate the PCI devices from Kernelflinger Crashmode.
This implementation shared some option with the legacy [pciutils - lspci](https://github.com/pciutils/pciutils).  this implementation uses the legacy method via I/O addresses `0xCF8` and `0xCFC` which should work on any hardware.

Crashmode: support the lspci shell command

---

kf4cic.c

StriCmp is not always a string compare function without case sensitivity.
Replace StriCmp with StrcaseCmp which is a string compare function
without case sensitivity.
Tracked-On: OAM-88246

kf4cic: change string compare function without case sensitivity

---

Android.mk

if BOARD_AVB_ENABLE isn't set, libavb do not need to be built
Tracked-On: OAM-88374

kf4cic: do not build libavb if BOARD_AVB_ENABLE not set

---

libkernelflinger/trusty_efi.c

The change only availbe for efi platform.
Barrier size will be increased to 2M in this case, thus trusty address
is 2M align in order to use big page table
Tracked-On: OAM-88853

boot: set Trusty memory size to 20M for rowhammer mitigation

---

Android.mk

boot: remove no-delete-null-pointer-checks build flags

---

Android.mk

Add the flags only if clang version bigger than 6
Tracked-On: OAM-90381

boot: Add no-delete-null-pointer-checks build flags

---

kf4cic.c

boot: boot_state should not dependence on RPMB storage

---

libkernelflinger/trusty_efi.c

To reduce the risk of seed and rpmb key leak, scrub seed and rpmb key
passed to TOS after TOS loaded.

scrub seed and rpmb key passed to TOS

---

libkernelflinger/vars.c

if the initial value of serial number is set to non-zero, the real
serial number will not be read.
Tracked-On: OAM-91337

set initial value of serial number to zeros

---

Android.mk

PRODUCTS.$(INTERNAL_PRODUCT).PRODUCT_SUPPORTS_VERITY is obsolete

Use the new PRODUCT_SUPPORTS_VERITY variable

---

include/tpm2_security.h
include/vars.h
kernelflinger.c
libkernelflinger/tpm2_security.c
libkernelflinger/vars.c

Kerneflinger: set bootloader to locked state on the first boot

---

libfastboot/fastboot_ui.c

the patch "UI: fit low resolution screen" cause some user build UI display error, need to be reverted

Revert "UI: fit low resolution screen"

---

libfastboot/fastboot_flashing.c

Kernelflinger: wipe metadata partition when device lock state changes

---

avb/libavb_ab/avb_ab_flow.c
avb/libavb_ab/avb_ab_flow.h
avb/libavb_ab/avb_ab_ops.h
include/android.h
kfld.c
libkernelflinger/slot_avb.c

Change bootloader control ab data structure to align with
android bootctrl 1.1

support android bootctrl 1.1

---

include/android.h
installer.c
kernelflinger.c
libkernelflinger/android.c

Changes:
1) support boot image version 3
2) load and verify vendor_boot partition
3) load generic ramdisk into memory immediately following the vendor ramdisk

Support vendor_boot partition

---

libkernelflinger/android.c

for boot image v3, the page size is always 4096

change page size of boot image v3 to 4096

---

avb/libavb_ab/avb_ab_flow.c

boot: set slot number to 2 for a/b slot implementation

---

avb/libavb_ab/avb_ab_flow.c

SetActiveBootSlot() of boot_control 1.1 always set slot
tries_remaining to 6.
Boot should be enabled in this case.

slot-ab: enable boot when tries > 1

---

libsslsupport/Android.mk

1. undefine __linux__ since kernerflinger doesn't dependence
on linux kernel
2. Disable __REMOVED_IN(23) to avoid borningssl build failure
Tracked-On: OAM-97093

kernelflinger: Fix compile issues.

---

libefiusb/device_mode/XdciDWC.c

EpNum shouldn't larger than (16 * 2), since basing on the usb
protocol, a USB device can only have up to 32 endpoints
(16 OUT and 16 IN).
Tracked-On: OAM-97425
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>

Check the value of EpNum before accessing the EpHandles
